from __future__ import annotations

import typing
from functools import partial
from PyQt6.QtWidgets import (
    QWidget, QHBoxLayout, QSizePolicy, QPushButton, QLabel, QVBoxLayout, QScrollArea, QMessageBox
)
from PyQt6 import QtCore

from widgets.vectordefiner import VectorDefinerAutoextend, VectorDefinerFixed
from widgets.vector_compare.progressholders import VectorComparingProgress
from widgets.vectordefined import VectorDefined
from widgets.vector_compare.resultholders import FourBasketResultHolder

from automata_graph.automata_renderer import VectorComparatorByCoordinate

if typing.TYPE_CHECKING:
    from main import Window

class VectorComparer(QWidget):
    def __init__(self, main_window: Window, parent: typing.Optional['QWidget'] = ...) -> None:
        super().__init__(parent)
        self.setup_ui()
        self.main_window = main_window
        self.defined_vectors: typing.List[VectorDefined] = []
        self.result_widget: typing.Optional[FourBasketResultHolder] = None
        self.progress_widget: typing.Optional[VectorComparingProgress] = None

    def lock_button_react(self):
        first_vector_line_edit = self.pivot_vector.line_edits[0]

        if first_vector_line_edit.text():
            self.lock_pivot_button.setDisabled(False)
        else:
            self.lock_pivot_button.setDisabled(True)

    def lock_pivot(self):
        if not self.pivot_vector.check_all_filled():
            _translate = QtCore.QCoreApplication.translate
            QMessageBox.warning(self, _translate("MainWindow", "Locking failed"), _translate("MainWindow", "Make sure all vector fields have numbers"))
            return

        last_line_edit = self.pivot_vector.line_edits[-1]
        _translate = QtCore.QCoreApplication.translate
        self.vector_definer.resize_vector(self.pivot_vector.vector_size)

        if last_line_edit.isEnabled():
            self.lock_pivot_button.setText(_translate("MainWindow", "Unlock"))
            self.pivot_vector.set_disable_input(True)
            self.vector_definer.set_disable_input(False)
            self.add_vector_button.setDisabled(False)
            self.vector_definer.fill_default()
        else:
            self.lock_pivot_button.setText(_translate("MainWindow", "Lock"))
            self.pivot_vector.set_disable_input(False)
            self.vector_definer.set_disable_input(True)
            self.add_vector_button.setDisabled(True)


    def remove_vector(self, defined_vector: VectorDefined):
        self.defined_vectors.remove(defined_vector)
        defined_vector.deleteLater()

    def add_vector(self):
        if not self.vector_definer.check_all_filled():
            _translate = QtCore.QCoreApplication.translate
            QMessageBox.warning(self, _translate("MainWindow", "Adding failed"), _translate("MainWindow", "Make sure all vector fields have numbers"))
            return

        new_defined_vector = VectorDefined(self.vector_definer.vector_data, self.added_vectors_area)
        self.added_vectors_layout.addWidget(new_defined_vector)
        new_defined_vector.pushButton.clicked.connect(partial(self.remove_vector, new_defined_vector))
        self.defined_vectors.append(new_defined_vector)

    def run_automata(self):
        self.run_button.setDisabled(True)
        self.add_vector_button.setDisabled(True)
        self.result_widget = FourBasketResultHolder(self.main_window.result_widget_holder)
        self.main_window.result_layout_holder.addWidget(self.result_widget)
        self.progress_widget = VectorComparingProgress(self.main_window.solving_progress_holder)
        self.main_window.solving_progress_layout.addWidget(self.progress_widget)
        self.solver = VectorComparatorByCoordinate(self, self.progress_widget, self.result_widget)
        self.solver.solution_step()



    

    def setup_ui(self):
        self.verticalLayout_10 = QVBoxLayout(self)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_10 = QWidget(self)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_8 = QVBoxLayout(self.widget_10)
        self.verticalLayout_8.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_8.setSpacing(2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_6 = QWidget(self.widget_10)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_6 = QVBoxLayout(self.widget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_11 = QWidget(self.widget_6)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_5 = QHBoxLayout(self.widget_11)
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scrollArea = QScrollArea(self.widget_11)
        self.scrollArea.setEnabled(True)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_6 = QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 352, 69))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_6.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_6.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.horizontalLayout_8 = QHBoxLayout(self.scrollAreaWidgetContents_6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pivot_vector = VectorDefinerAutoextend(self.scrollAreaWidgetContents_6)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pivot_vector.sizePolicy().hasHeightForWidth())
        self.pivot_vector.setSizePolicy(sizePolicy)
        self.pivot_vector.setObjectName("pivot_vector")
        self.horizontalLayout_8.addWidget(self.pivot_vector, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_6)
        self.horizontalLayout_5.addWidget(self.scrollArea)
        self.verticalLayout_6.addWidget(self.widget_11)
        self.widget_12 = QWidget(self.widget_6)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_4 = QHBoxLayout(self.widget_12)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_13 = QWidget(self.widget_12)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_13.sizePolicy().hasHeightForWidth())
        self.widget_13.setSizePolicy(sizePolicy)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_6 = QHBoxLayout(self.widget_13)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QLabel(self.widget_13)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.horizontalLayout_4.addWidget(self.widget_13)
        self.lock_pivot_button = QPushButton(self.widget_12)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lock_pivot_button.sizePolicy().hasHeightForWidth())
        self.lock_pivot_button.setSizePolicy(sizePolicy)
        self.lock_pivot_button.setObjectName("lock_pivot_button")
        self.horizontalLayout_4.addWidget(self.lock_pivot_button)
        self.verticalLayout_6.addWidget(self.widget_12)
        self.verticalLayout_8.addWidget(self.widget_6)
        self.widget_7 = QWidget(self.widget_10)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_7 = QVBoxLayout(self.widget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_15 = QWidget(self.widget_7)
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_10 = QHBoxLayout(self.widget_15)
        self.horizontalLayout_10.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.scrollArea_2 = QScrollArea(self.widget_15)
        self.scrollArea_2.setEnabled(True)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_7 = QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 352, 69))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_7.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_7.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.horizontalLayout_11 = QHBoxLayout(self.scrollAreaWidgetContents_7)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.vector_definer = VectorDefinerFixed(self.scrollAreaWidgetContents_7)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vector_definer.sizePolicy().hasHeightForWidth())
        self.vector_definer.setSizePolicy(sizePolicy)
        self.vector_definer.setObjectName("vector_definer")
        self.horizontalLayout_11.addWidget(self.vector_definer, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_7)
        self.horizontalLayout_10.addWidget(self.scrollArea_2)
        self.verticalLayout_7.addWidget(self.widget_15)
        self.widget_17 = QWidget(self.widget_7)
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_13 = QHBoxLayout(self.widget_17)
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.widget_18 = QWidget(self.widget_17)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_18.sizePolicy().hasHeightForWidth())
        self.widget_18.setSizePolicy(sizePolicy)
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_14 = QHBoxLayout(self.widget_18)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_2 = QLabel(self.widget_18)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_14.addWidget(self.label_2)
        self.horizontalLayout_13.addWidget(self.widget_18)
        self.add_vector_button = QPushButton(self.widget_17)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_vector_button.sizePolicy().hasHeightForWidth())
        self.add_vector_button.setSizePolicy(sizePolicy)
        self.add_vector_button.setObjectName("add_vector_button")
        self.horizontalLayout_13.addWidget(self.add_vector_button)
        self.verticalLayout_7.addWidget(self.widget_17)
        self.verticalLayout_8.addWidget(self.widget_7)
        self.label_3 = QLabel(self.widget_10)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.scrollArea_3 = QScrollArea(self.widget_10)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.scrollArea_3.sizePolicy().hasHeightForWidth())
        self.scrollArea_3.setSizePolicy(sizePolicy)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_8 = QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 370, 534))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.verticalLayout_9 = QVBoxLayout(self.scrollAreaWidgetContents_8)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.added_vectors_area = QWidget(self.scrollAreaWidgetContents_8)
        self.added_vectors_area.setObjectName("added_vectors_area")
        self.added_vectors_layout = QVBoxLayout(self.added_vectors_area)
        self.added_vectors_layout.setContentsMargins(4, 4, 4, 4)
        self.added_vectors_layout.setSpacing(2)
        self.added_vectors_layout.setObjectName("added_vectors_layout")
        self.verticalLayout_9.addWidget(self.added_vectors_area, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_8)
        self.verticalLayout_8.addWidget(self.scrollArea_3)
        self.widget_3 = QWidget(self.widget_10)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QHBoxLayout(self.widget_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.test_button = QPushButton(self.widget_3)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_button.sizePolicy().hasHeightForWidth())
        self.test_button.setSizePolicy(sizePolicy)
        self.test_button.setObjectName("test_button")
        self.horizontalLayout.addWidget(self.test_button)
        self.widget_5 = QWidget(self.widget_3)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout.addWidget(self.widget_5)
        self.run_button = QPushButton(self.widget_3)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_button.sizePolicy().hasHeightForWidth())
        self.run_button.setSizePolicy(sizePolicy)
        self.run_button.setObjectName("run_button")
        self.horizontalLayout.addWidget(self.run_button)
        self.verticalLayout_8.addWidget(self.widget_3)
        self.verticalLayout_10.addWidget(self.widget_10)

        self.lock_pivot_button.clicked.connect(self.lock_pivot)
        self.add_vector_button.clicked.connect(self.add_vector)
        self.run_button.clicked.connect(self.run_automata)
        
        self.retranslate_ui()

    def retranslate_ui(self):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("MainWindow", "Pivot vector"))
        self.lock_pivot_button.setText(_translate("MainWindow", "Lock"))
        self.label_2.setText(_translate("MainWindow", "Add vector to set"))
        self.add_vector_button.setText(_translate("MainWindow", "Add"))
        self.label_3.setText(_translate("MainWindow", "Added vectors"))
        self.test_button.setText(_translate("MainWindow", "Test"))
        self.run_button.setText(_translate("MainWindow", "Run!"))