import typing
import typing_extensions
from PyQt6.QtWidgets import (
    QWidget, QHBoxLayout, QSizePolicy, QLabel, QVBoxLayout, QScrollArea
)
from PyQt6 import QtCore

class ThreeBasketResultHolder(QWidget):
    def __init__(self, parent: typing.Optional['QWidget'] = ...) -> None:
        super().__init__(parent)
        self.setup_ui()

    def add_result(self, vector: typing.List[int], basket: typing_extensions.Literal[1, 2, 3]):
        if basket == 1:
            new_label_vector = QLabel(self.v1_container)
            self.v1_layout.addWidget(new_label_vector)
            new_label_vector.setText(f"({', '.join(str(a) for a in vector)})")
        
        elif basket == 2:
            new_label_vector = QLabel(self.v2_container)
            self.v2_layout.addWidget(new_label_vector)
            new_label_vector.setText(f"({', '.join(str(a) for a in vector)})")
        
        elif basket == 3:
            new_label_vector = QLabel(self.v3_container)
            self.v3_layout.addWidget(new_label_vector)
            new_label_vector.setText(f"({', '.join(str(a) for a in vector)})")

    def setup_ui(self):
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.horizontalLayout = QHBoxLayout(self)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.widget = QWidget(self)
        self.widget.setObjectName("widget_8")
        self.verticalLayout = QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout_10")
        self.label = QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label)
        self.scrollArea = QScrollArea(self.widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 271, 212))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents_9")
        self.verticalLayout_2 = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_17")
        self.v1_container = QWidget(self.scrollAreaWidgetContents)
        self.v1_container.setObjectName("v1_container")
        self.v1_layout = QVBoxLayout(self.v1_container)
        self.v1_layout.setObjectName("verticalLayout_18")
        self.verticalLayout_2.addWidget(self.v1_container, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QWidget(self)
        self.widget_2.setObjectName("widget_9")
        self.verticalLayout_4 = QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_11")
        self.label_2 = QLabel(self.widget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_2)
        self.scrollArea_2 = QScrollArea(self.widget_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 271, 212))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_10")
        self.verticalLayout_5 = QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_16")
        self.v2_container = QWidget(self.scrollAreaWidgetContents_2)
        self.v2_container.setObjectName("v2_container")
        self.v2_layout = QVBoxLayout(self.v2_container)
        self.v2_layout.setObjectName("verticalLayout_19")
        self.verticalLayout_5.addWidget(self.v2_container, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_3 = QWidget(self)
        self.widget_3.setObjectName("widget_14")
        self.verticalLayout_7 = QVBoxLayout(self.widget_3)
        self.verticalLayout_7.setObjectName("verticalLayout_13")
        self.label_3 = QLabel(self.widget_3)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_19")
        self.verticalLayout_7.addWidget(self.label_3)
        self.scrollArea_3 = QScrollArea(self.widget_3)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 271, 212))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_11")
        self.verticalLayout_8 = QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_15")
        self.v3_container = QWidget(self.scrollAreaWidgetContents_3)
        self.v3_container.setObjectName("v3_container")
        self.v3_layout = QVBoxLayout(self.v3_container)
        self.v3_layout.setObjectName("verticalLayout_20")
        self.verticalLayout_8.addWidget(self.v3_container, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_7.addWidget(self.scrollArea_3)
        self.horizontalLayout.addWidget(self.widget_3)

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("MainWindow", "V1 (less than hyperplane)"))
        self.label_2.setText(_translate("MainWindow", "V2 (greater than hyperplane)"))
        self.label_3.setText(_translate("MainWindow", "V3 (on the hyperplane)"))