import typing
from PyQt6.QtWidgets import (
    QWidget, QHBoxLayout, QSizePolicy, QLabel, QVBoxLayout, QScrollArea
)
from PyQt6 import QtCore

class VectorComparingProgress(QWidget):
    def __init__(self, parent: typing.Optional['QWidget'] = ...) -> None:
        super().__init__(parent)
        self.setup_ui()

    def setup_ui(self):
        self.horizontalLayout_12 = QHBoxLayout(self)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.widget_5 = QWidget(self)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_15 = QHBoxLayout(self.widget_5)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.widget_9 = QWidget(self.widget_5)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_10 = QVBoxLayout(self.widget_9)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_4 = QLabel(self.widget_9)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.label_18 = QLabel(self.widget_9)
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_10.addWidget(self.label_18)
        self.label_19 = QLabel(self.widget_9)
        self.label_19.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_10.addWidget(self.label_19)
        self.horizontalLayout_15.addWidget(self.widget_9)
        self.widget_14 = QWidget(self.widget_5)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_14.sizePolicy().hasHeightForWidth())
        self.widget_14.setSizePolicy(sizePolicy)
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_11 = QVBoxLayout(self.widget_14)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.current_pivot_vector = QLabel(self.widget_14)
        self.current_pivot_vector.setText("")
        self.current_pivot_vector.setObjectName("current_pivot_vector")
        self.verticalLayout_11.addWidget(self.current_pivot_vector)
        self.current_comparing_vector = QLabel(self.widget_14)
        self.current_comparing_vector.setText("")
        self.current_comparing_vector.setObjectName("current_comparing_vector")
        self.verticalLayout_11.addWidget(self.current_comparing_vector)
        self.current_comparison_results = QLabel(self.widget_14)
        self.current_comparison_results.setText("")
        self.current_comparison_results.setObjectName("current_comparison_results")
        self.verticalLayout_11.addWidget(self.current_comparison_results)
        self.horizontalLayout_15.addWidget(self.widget_14)
        self.horizontalLayout_12.addWidget(self.widget_5)
        self.widget_8 = QWidget(self)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_29 = QHBoxLayout(self.widget_8)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.widget_19 = QWidget(self.widget_8)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_19.sizePolicy().hasHeightForWidth())
        self.widget_19.setSizePolicy(sizePolicy)
        self.widget_19.setObjectName("widget_19")
        self.verticalLayout_13 = QVBoxLayout(self.widget_19)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_26 = QLabel(self.widget_19)
        self.label_26.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_13.addWidget(self.label_26)
        self.label_27 = QLabel(self.widget_19)
        self.label_27.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_13.addWidget(self.label_27)
        self.label_28 = QLabel(self.widget_19)
        self.label_28.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_13.addWidget(self.label_28)
        self.horizontalLayout_29.addWidget(self.widget_19)
        self.widget_16 = QWidget(self.widget_8)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_16.sizePolicy().hasHeightForWidth())
        self.widget_16.setSizePolicy(sizePolicy)
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_12 = QVBoxLayout(self.widget_16)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.current_pivot_vector_coordinate = QLabel(self.widget_16)
        self.current_pivot_vector_coordinate.setText("")
        self.current_pivot_vector_coordinate.setObjectName("current_pivot_vector_coordinate")
        self.verticalLayout_12.addWidget(self.current_pivot_vector_coordinate)
        self.current_comparing_vector_coordinate = QLabel(self.widget_16)
        self.current_comparing_vector_coordinate.setText("")
        self.current_comparing_vector_coordinate.setObjectName("current_comparing_vector_coordinate")
        self.verticalLayout_12.addWidget(self.current_comparing_vector_coordinate)
        self.current_binary_comparing = QLabel(self.widget_16)
        self.current_binary_comparing.setText("")
        self.current_binary_comparing.setObjectName("current_binary_comparing")
        self.verticalLayout_12.addWidget(self.current_binary_comparing)
        self.horizontalLayout_29.addWidget(self.widget_16)
        self.horizontalLayout_12.addWidget(self.widget_8)

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.label_4.setText(_translate("MainWindow", "Pivot vector:"))
        self.label_18.setText(_translate("MainWindow", "Comparing vector:"))
        self.label_19.setText(_translate("MainWindow", "Comparison results:"))
        self.label_26.setText(_translate("MainWindow", "Pivot vector coordinate:"))
        self.label_27.setText(_translate("MainWindow", "Comparing vector coordinate:"))
        self.label_28.setText(_translate("MainWindow", "Currently comparing:"))